name: Crafting Cost Optimization

# Run workflow on push to main branch or manually
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Run the optimizer script
      - name: Run Craft Optimizer
        run: |
          mkdir -p output
          python scripts/craft_optimizer.py > output/optimizer_output.txt
          # Save CSV if script generates it
          if [ -f scripts/best_worst_recipes.csv ]; then
              cp scripts/best_worst_recipes.csv output/
          fi

      # Step 5: Upload artifacts
      - name: Upload optimizer results
        uses: actions/upload-artifact@v3
        with:
          name: optimizer-results
          path: output/
